### ISSUE TITLE
hard-coded file name in post-user-setup

### ISSUE THREAD

**Issue by wanxewoj** [zhiverbox/armbian-userpatches#6]
https://github.com/zhiverbox/armbian-userpatches/blob/ce7d6737b20777194549eb88d613ee3cf1cec4e4/overlay/opt/zhiverbox/scripts/etc/profile.d/z_10_post_user_setup_customization.sh#L12

`z_10_post_user_setup_customization.sh` expects the ssh public key to have the hard-coded name `id_ecdsa.pub` while the installer (`install-zhiverbox.sh`) script allows the user to select any `*.pub` file:
https://github.com/zhiverbox/armbian-build/blob/34246b77e521a281058f849a8dc0f38ca5d7af59/install-zHIVErbox.sh#L1686

Hence, for example users selecting a `id_rsa.pub` key during the image customization run into an error (file not found) during the post user setup.

**Comment by zciendor** [comment]
Thanks for raising this! The installer and this script should be in sync now and allow for any public key to be selected.
